"""
Randomly searches for a doujin. does NOT grab doujins with "loli" or "shota" in the tags
"""
import discord
from random import randint

from pasta.helpers.nsfw.hentai.sauce import Sauce
from pasta.helpers.nsfw.search import Search

class randomSearch:
	def __init__(self):
		pass
	
	# get one random sauce
	async def noArgs(self, ctx):
		print("fetching...")
		sauce = Sauce(str(randint(10000, 999999)))
		# make sure it exists
		while (not sauce.doesExist()) or sauce.isIllegal():
			sauce = Sauce(str(randint(10000, 999999)))

		await ctx.send(embed=sauce.getEmbed())
	
	# get amount sauce of a search criteria
	async def yesArgs(self, ctx, amount, criteria):
		find = Search(criteria)
		embeds = find.getRandSauce(amount)
		# make sure the embed will be valid
		if find.doesExist() and len(embeds) > 0:
			for embed in embeds:
				await ctx.send(embed=embed)
		elif len(embeds) < amount:
			await ctx.send("||Unfortunately, {rm} doujins have been removed from this search due to the quantity of loli or shota doujins generated by the 25-maximum search. Use .readme for more info||".format(rm=amount-len(embeds)))
		else:
			await ctx.send("Found no `{criteria}`".format(criteria=criteria))